# Generated by Django 4.0.4 on 2022-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aucun', max_length=50, null=True)),
                ('year_from_bac', models.SmallIntegerField(default=0, help_text='year since le bac', null=True, verbose_name='year')),
                ('scholar_year', models.CharField(default='0000-00001', max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(null=True, verbose_name='date of birth')),
                ('last_name', models.CharField(default='???', help_text='last name of the student', max_length=255, verbose_name='lastname')),
            ],
        ),
    ]
