# Generated by Django 4.0.4 on 2022-04-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, default='', help_text='some comments about the student', max_length=255, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='x@y.z', help_text='phone number of the student', max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0999999999', help_text='phone number of the student', max_length=10, verbose_name='phonenumber'),
        ),
    ]
